name: 'Escape Markdown for Usage in JSON'
description: 'A simple action to escape quotes and other characters within markdown so it can be using within a JSON'
inputs:
  markdown:  # id of input
    description: 'The entry from the changelog that we need to escaped'
    required: true
outputs:
  escaped_markdown: # output will be available to future steps
    description: 'The escaped entry'
runs:
  using: 'node16'
  main: 'dist/index.js'
